### ISSUE TITLE
date format for list items has changed

### ISSUE THREAD

**Issue by chrisdeyloff** [rstedman/tfs-pullrequest-dashboard#1]
It looks like the date format for list items has changed from MM/dd/yyyy TO dd/MM/yyyy.  Can you change it back MM/dd/yyyy or provide a setting to set the format?  Thank you!

**Comment by rstedman** [comment]
Looking through the history, it seems it has always used the date format "dd/MM/yyyy", and I don't remember using a different format at any point.

That said, I'll look into making this configurable as a preference when I get the chance.

**Comment by rstedman** [comment]
Version 1.1.0 of the Pull Request Dashboard plugin has been published to the visual studio marketplace, which has a new settings dropdown which allows a user to change the date format setting used when displaying PR creation date timestamps
