### ISSUE TITLE
Issue with layout after long running read process

### ISSUE THREAD

**Issue by ryanpeters74** [rstedman/tfs-pullrequest-dashboard#21]
Recently the dashboard has been very slow to load and when it does the font and layout are not normal and there is a very small grey button with no text on it that displays with a tooltip of "Settings".

**Comment by rstedman** [comment]
Is this this occurring on a standalone TFS deployment, or in VSTS?  Also, can you provide a screenshot of what you are seeing, as well as any errors that print out in the console when you have developer tools open.

**Comment by rstedman** [comment]
closing due to lack of additional information
