### ISSUE TITLE
Display also completed pull requests

### ISSUE THREAD

**Issue by peef** [rstedman/tfs-pullrequest-dashboard#22]
Now the extension displays only active PRs. Would be nice to have some switch or tab in UI where completed PRs are displayed.

**Comment by rstedman** [comment]
Showing completed pull requests does not fit with the goals of this extension.  This extension is focused on displaying pull requests that are currently active to provide a concise UI for developers to see any active pull requests they may be interested/involved in.

There is another extensions that may provide what you're looking for: [Pull Request Search](https://marketplace.visualstudio.com/items?itemName=ottostreifel.pull-request-search-onprem#overview).
