### ISSUE TITLE
Switching between TFS Projects resets the selected repos

### ISSUE THREAD

**Issue by patrious** [rstedman/tfs-pullrequest-dashboard#23]
When I switch between TFS projects at my workplace, the selected repos for the PR-Dashboard are reset to selecting all of them. 

For Example
Proj - A ( 100 Repos, 5 Selected )
switch to Proj - B
Proj - B ( 10 Repos, 10 Selected )
switch to Proj - A
Proj - A ( 100 Repos, 100 Selected )

**Comment by rstedman** [comment]
The default behavior of the dashboard is to only show the repositories associated to the project you have selected.  You can however override this behavior by checking the "All Projects" setting in the user settings dropdown at the top right of the dashboard:
![image](https://user-images.githubusercontent.com/5440997/41365699-1873a59a-6f08-11e8-92c0-8c680746311f.png)
