### ISSUE TITLE
Does not work over HTTPs

### ISSUE THREAD

**Issue by stickleprojects** [rstedman/tfs-pullrequest-dashboard#24]
Loading over HTTPs TFS, you see the spinning loader graphic, but nothing more. Debug console shows the following:

![image](https://user-images.githubusercontent.com/11067183/42639549-2cbf1ef2-85e8-11e8-85a4-a15c08af2e00.png)

**Comment by rstedman** [comment]
This appears to be an issue with your TFS instance, likely some misconfiguration.  The index.html is the entry point for this extension, TFS handles how that is loaded, I have no control over that.  

The organization I work at uses this extension, and our TFS instance is served over HTTPS.  There are no issues loading this extension, and I confirmed that the same index.html resource is being requested over https, not http.
