### ISSUE TITLE
Does not work with the new Azure DevOps base URL - dev.azure.com/organisation instead of organisation.visualstudio.com

### ISSUE THREAD

**Issue by stylesm** [rstedman/tfs-pullrequest-dashboard#26]
Navigating to an opened pull request in Chrome from the Pull Request Dashboard (e.g. https://dev.azure.com/org/project/_git/repo/pullrequest/2146), I get the following error. This occurs in Chrome, IE, but not Edge, Firefox. It is happening for all of our developers on both work/personal devices on/off the site network.

This only occurs using the new dev.azure.com URL. The PR loads fine using https://org.visualstudio.com/project/_git/repo/pullrequest/2146.

The error text is:

An unexpected error has occurred within this region of the page. You can try reloading this component or refreshing the entire page.

[Refresh page] [Reload component]

Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://dev.azure.com/org/project/_git/repo/pullrequest/2146' cannot be created in a document with origin 'https://dev.azure.com' and URL 'https://org@dev.azure.com/org/project/_git/repo/pullrequest/2146'. Stack in t in u in t in u in div in t in t in div in t in u in div in t in u in div in t in u in div in t in t

![image](https://user-images.githubusercontent.com/5602910/48131819-4ae94a80-e289-11e8-96c7-7b65e202c35b.png)

Logging out/back in, clearing browser cache, etc doesn't appear to work.

**Comment by rstedman** [comment]
Version 2.0.5 of this extension has been released which addresses this issue.

**Comment by adhamenaya** [comment]
hi, @rstedman I have the same issue, but which extension are you talking about and how can I use it?
