### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by samneirinck** [rstedman/tfs-pullrequest-dashboard#28]
Recently, Azure Devops [introduced](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sprint-142-update#dark-theme) dark theme support. 

Would it be possible to also support a dark theme when the user specified this in his/her preferences?

**Comment by edufur** [comment]
would really love the dark theme support!! please and thank you.

**Comment by rstedman** [comment]
theming support added in v2.4.0
