### ISSUE TITLE
readme.md and running locally

### ISSUE THREAD

**Issue by mbschenkel** [rstedman/tfs-pullrequest-dashboard#3]
I was trying to run the extension locally, following the section "running locally" in the readme.md.
However, it appears that the text doesn't match the code: 
- Should "src/app/app.ts" be changed to "src/app/appconfig.service.ts"?
- Should "AppConfigSettings" be changed to "AppConfigService"?
- Should "... run serve" be changed to ".. run start"?

Also when starting I get several errors, the first one being
```
[mypath]/tfs-pullrequest-dashboard/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

**Comment by rstedman** [comment]
Yes, the readme is incorrect, thanks for catching that.  I did some refactoring & forgot to update the readme.  I've pushed a commit that fixes the issues you've pointed out (c045d677862fe4a2d4c39f145c531d9421a20ec4).

Also, the error you were running into appears to be an issue between new minor versions of some third party dependencies.  I've updated the versions of the dependency that was causing an issue, and updated my package.json to remove version ranges from my third party dependencies, instead using fixed versions, to avoid this kind of problem in the future (e1b51242629af9790459a6b7c674e9fd70e2c80f).
