### ISSUE TITLE
Add Draft indicator for PRs in Draft mode

### ISSUE THREAD

**Issue by sadukie** [rstedman/tfs-pullrequest-dashboard#36]
When a PR is in draft mode, it would be helpful to have a Draft indicator.  This is an example of a PR in draft mode:

![image](https://user-images.githubusercontent.com/106202/55632400-35b90f00-5788-11e9-8bd0-381078ed860f.png)

Currently in the tfs-pullrequest-dashboard:

![image](https://user-images.githubusercontent.com/106202/55633191-cd6b2d00-5789-11e9-9031-5051f273191b.png)

It would be helpful to see this is in draft mode.  Perhaps a notification like this:

![image](https://user-images.githubusercontent.com/106202/55633351-2a66e300-578a-11e9-81d0-46b81a509fc2.png)

**Comment by OneCyrus** [comment]
draft indicator would be very handy

**Comment by rstedman** [comment]
draft indicator added in version 2.1.0
