### ISSUE TITLE
Bug: Changing reviewer status in a branch policy isn't updating reviewers for open PRs

### ISSUE THREAD

**Issue by sadukie** [rstedman/tfs-pullrequest-dashboard#37]
Given I am on the dashboard screen
And I have PRs in a `master` branch that currently has required reviewers
When I change the `master` branch to mark those reviewers optional
Then I expect the reviewers to appear as optional in the Dashboard

--------

Here's our current situation:
![image](https://user-images.githubusercontent.com/106202/55819650-47235380-5ac7-11e9-93ce-4c5e93a79277.png)

* RepoName `master` has branch policies with Reviewer1 and Reviewer2 required.
* We updated RepoName `master` branch policies to make them optional.
* We abandoned the PR and reactivated it for the branch policies to be applied to the PR.
* I went back to the dashboard and still saw:

![image](https://user-images.githubusercontent.com/106202/55819799-923d6680-5ac7-11e9-8c73-5cd76412f3f4.png)

I was expecting to see:

![image](https://user-images.githubusercontent.com/106202/55819827-ac774480-5ac7-11e9-9c9e-17834bd1edd0.png)

**Comment by TheConstructor** [comment]
Does it show correctly when opening the PR? I think TFS/Azure DevOps does not immediately update existing PRs.
