### ISSUE TITLE
Outage?

### ISSUE THREAD

**Issue by slatted** [rstedman/tfs-pullrequest-dashboard#38]
The extension directly gets an error, but does load, but the Dashboard Widgets are erroring out.

![image](https://user-images.githubusercontent.com/24395356/56502068-14be2100-64df-11e9-9586-70bed0978e6b.png)
![image](https://user-images.githubusercontent.com/24395356/56502116-3c14ee00-64df-11e9-8775-6f4785e1e1d8.png)

**Comment by snowadamc** [comment]
I also had this error. Looking forward to an update.

**Comment by rstedman** [comment]
Addressed in released version 2.0.6

**Comment by slatted** [comment]
Thank you sir!

**Comment by patriked** [comment]
We still get this error in the dashboard widget.

**Comment by rstedman** [comment]
> We still get this error in the dashboard widget.

Try ctrl+f5 in your browser when viewing the dashboard to ensure you're loading the latest version. It seems like the default behavior of azure devops for extensions is to tell the browser to cache content for 1yr.  So you need to force a refresh of your local cache to ensure you get the latest code.
