### ISSUE TITLE
Minimal permission scopes

### ISSUE THREAD

**Issue by hacst** [rstedman/tfs-pullrequest-dashboard#42]
Is it possible to reduce the permissions scope of this extension from ```vso.code``` to ```vso.code_status``` or does this scope lack anything essential?

```vso.code``` also include permissions to read the full source code which is quite a dangerous permission to have.

**Comment by rstedman** [comment]
I looked into using the code_status scope, but it isn't enough. It doesn't allow the extension to list all the repositories in a project. That was just the first error I encountered, there may be other issues in using that scope.

**Comment by hacst** [comment]
Bummer. Thanks for checking.
