### ISSUE TITLE
The number of codecoverage badges seems excessive

### ISSUE THREAD

**Issue by nertner** [rstedman/tfs-pullrequest-dashboard#49]
The number of codecoverage badges seems excessive.  May I request changing it to a badge with number instead of a badge for every "statuses" response?  ex. [codecoverage (19)]

![image](https://user-images.githubusercontent.com/3586334/62304464-debfff80-b432-11e9-80e1-484cfa91ff86.png)

_Originally posted by @nertner in https://github.com/rstedman/tfs-pullrequest-dashboard/issues/48#issuecomment-517327458_

**Comment by dbJones77** [comment]
This occurs when branch policy set for build validation or status validation. 

If status validation is turned on, you can have multiple "quality gate" badges, in both red and green, making it difficult to tell what the *current* quality gate status is on the dashboard.

![image](https://user-images.githubusercontent.com/56601897/66858930-2557cd00-ef3f-11e9-8705-674d8be1d542.png)

**Comment by TFeld00** [comment]
If using status validation, the pull request itself has an iteration number.
Each status can also be assigned a certain iteration, which would make it possible to only show the status of the current PR iteration.

**Comment by rstedman** [comment]
addressed in 2.4.1. Only the most recent status per unique status name will be displayed.
