### ISSUE TITLE
The list of repositories is not displayed

### ISSUE THREAD

**Issue by dduhanov** [rstedman/tfs-pullrequest-dashboard#50]
Hi, 

We use:
1) Azure DevOps Server Version 17.143.28912.1, 
2) Pull Request Dashboard version 2.3.1.

And one of the users sees the following:
![attachments](https://user-images.githubusercontent.com/23641720/63679120-42063d00-c7f9-11e9-8ff7-dbb185ca1af8.png)

He has access to all repositories in the project.
The problem is reproduced in the latest version of Chrome as well as IE, and on different operating systems (Win 10 / Ubuntu).

We tried to re-issued permissions to the project for the user, but it did not help.
Clearing the cache (ctrl+F5) doesn't help.

One HTTP GET 404 error:
Request URL: https://**CollectionName**/_apis/ExtensionManagement/InstalledExtensions/ryanstedman/tfs-pullrequest-dashboard/Data/Scopes/User/Me/Collections/%24settings/Documents/allProjects

Message: "TF1590005: Document with id $settings does not exist in collection User for {GUID} = dateFormat"

You do not know how to solve this problem?

**Comment by rstedman** [comment]
Could this user try selecting the "All Projects" setting:

![image](https://user-images.githubusercontent.com/5440997/70394844-e128fc00-19c6-11ea-9b71-dfd77b2a950b.png)

does this allow the user to see any repos in the dropdown?

**Comment by dduhanov** [comment]
Hi!
We solved this problem. Thanks!

**Comment by mariobrosch** [comment]
> Hi!
> We solved this problem. Thanks!

How did you solve this issue?
