### ISSUE TITLE
Enhancement : Show creation date of PR

### ISSUE THREAD

**Issue by FredDgrv** [rstedman/tfs-pullrequest-dashboard#51]
During daily meetings, we review PR and inspect old PR.

Information such as creation date or an indication how old is a PR would be assist to do that requirement.

**Comment by rstedman** [comment]
The creation date of PRs is currently shown in the hub view of the extension:
![image](https://user-images.githubusercontent.com/5440997/70394795-57792e80-19c6-11ea-9da1-aff689d17fab.png)

PRs in each category are also sorted by creation date - oldest first.
