### ISSUE TITLE
Support "Assigned to my team" in Azure DevOps

### ISSUE THREAD

**Issue by IvanAlekseev** [rstedman/tfs-pullrequest-dashboard#60]
Looks like there is an api to get all PRs assigned to particular team across all repos - https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/get%20pull%20requests%20by%20project?view=azure-devops-rest-5.1

Can it be used?

**Comment by tddorgtfo** [comment]
Duplicate of #46

**Comment by rstedman** [comment]
closing as duplicate
