### ISSUE TITLE
it would be great to see the percentages of PR

### ISSUE THREAD

**Issue by rifaterdemsahin** [rstedman/tfs-pullrequest-dashboard#9]
Accepted denied percentage for periods of time.

Our complaint is most of the things gets approved and we can not measure that.

**Comment by rstedman** [comment]
It sounds like you're looking for some kind of reporting tool that can give you a historical view of PRs that have already been closed.  That falls outside of the scope of what this extension is trying to accomplish, which is to give a useful display of current in progress pull requests.  This is not a feature that fits for this extension.
